# cx
    
server:
  port: 10001

spring:
  application:
    name: cx
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    cx:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/financeclear?characterEncoding=utf8&useUnicode=true&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false&useServerPrepStmts=true&allowMultiQueries=true
      username: root
      password: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    password: 
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 2000
  mvc:
    throw-exception-if-no-handler-found: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    username: u1
    password: something

endpoints:
  shutdown:
    enabled: true
    
optionFilePath:
  system: "/home/u2/cx/optionFile/system/option.json"
  article: "/home/u2/cx/optionFile/article/option.json"
  articleComment: "/home/u2/cx/optionFile/articleComment/option.json"
  mail: "/home/u2/cx/optionFile/mail/option.json"
  cloudinary: "/home/u2/cx/optionFile/cloudinary/option.json"
  automationTest: "/home/u2/cx/optionFile/automationTest/option.json"
  cryptoCoin: "/home/u2/cx/optionFile/cryptoCoin/option.json"
  currencyExchangeRate: "/home/u2/cx/optionFile/currencyExchangeRate/option.json"
  telegram: "/home/u2/cx/optionFile/telegram/option.json"
  tool: "/home/u2/cx/optionFile/tool/option.json"
  educate: "/home/u2/cx/optionFile/educate/option.json"
  joy: "/home/u2/cx/optionFile/joy/option.json"
  joyGarden: "/home/u2/cx/optionFile/joy/gardenOption.json"
  openAI: "/home/u2/cx/optionFile/openAI/option.json"
  
    
logging:
  level: 
    root: ERROR 
    org.springframework.web: ERROR
    # demo.test.controller: DEBUG
    demo.test.mapper: ERROR
    demo.tool.mapper: ERROR
    # demo.finance.cryptoCoin.notice.mapper: DEBUG
    # demo.finance.cryptoCoin.data.mapper: DEBUG
    # demo.mapper: DEBUG
    # demo.joy.garden.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%p] [%d{yyyy-MM-dd HH:mm:ss}][%c]%m%n [%thread] %-5level %logger{36}"
      
  file.name: /home/u2/logs/cx.log